CREATE TABLE employees ( EmployeeID INT PRIMARY KEY Identity(1,1), 
FIRST_NAME  VARCHAR(20) NOT NULL, 
LAST_NAME  VARCHAR(25) NOT NULL, 
EMAIL  VARCHAR(25) NOT NULL, 
PHONE_NUMBER  VARCHAR(10) NOT NULL, 
HIRE_DATE date NOT NULL, 
JOB_ID INT NOT NULL, 
SALARY DECIMAL(8,2) NOT NULL,
COMMISSION_PER DECIMAL(5,2) NOT NULL,
MANAGER_ID INT NOT NULL, 
DEPARTMENT_ID INT NOT NULL, 


CONSTRAINT FK_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID),
CONSTRAINT FK_JOB_ID FOREIGN KEY (JOB_ID) REFERENCES jobs(JOB_ID)
);

CREATE TABLE departments ( DEPARTMENT_ID INT PRIMARY KEY Identity(1,1));
