USE [Day-1]

CREATE TABLE JOBS
(
JobId INT PRIMARY KEY IDENTITY(1,1),
JobTitle VARCHAR(10) NOT NULL DEFAULT ' ',
MinSalary DECIMAL(6,0) DEFAULT NULL,
MaxSalary DECIMAL(6,0) DEFAULT 8000
);

INSERT INTO JOBS VALUES ('developer',4000,10000)

SELECT * FROM JOBS
